version: "3.7"
services:
  web:
    build:
      context: ./web
    command: node index.js
    environment:
     - API_URL=http://api:3001/data
    volumes:
     - ./web:/app
    ports:
      - "80:3000"
    networks:
      - public-network
    depends_on:
     - api

  api:
    build:
      context: ./api
    command: node index.js
    environment: 
    - CONNECTION_STRING=postgres://postgres:postgres@db/postgres_db
    ports:
      - "3001:3001"
    networks:
      - private-network
      - public-network
    depends_on:
     - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres_db"
    volumes:
      - "/home/ubuntu/english2arabic-belt3/sql_scripts/:/docker-entrypoint-initdb.d"
    ports: ["5432"]
    networks:
      - private-network

volumes:
  db-data:

networks:
  public-network:
   driver: bridge

  private-network:
   driver: bridge