version: "3.7"
services:
  web:
    build:
      context: ./web
    command: node index.js
    volumes:
     - ./web:/app
    ports:
      - "80:3000"
    networks:
      - public-network
      - private-network
    depends_on:
     - db

  api:
    build:
      context: "API_URL=http://api:3001/data" 
    command: node index.js
    environment: 
    - CONNECTION_STRING=postgres://demo_user:demo_user@db/demo_db
    ports:
      - "3001:80"
    networks:
      - private-network
    depends_on:
     - db

  db:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
      # to intialize the sql data
      # - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432"
    networks:
      - private-network

volumes:
  db-data:

networks:
  public-network: 
   - driver: bridge 
  private-network:
  - driver: bridge 
